const VITE_ATM_URL = import.meta.env.VITE_ATM_URL;
const VITE_ACCOUNTS_URL = import.meta.env.VITE_ACCOUNTS_URL;
const VITE_TRANSFER_URL = import.meta.env.VITE_TRANSFER_URL;
const VITE_LOAN_URL = import.meta.env.VITE_LOAN_URL;
const VITE_COGNITO_USER_POOL_ID = import.meta.env.VITE_COGNITO_USER_POOL_ID
const VITE_COGNITO_CLIENT_ID = import.meta.env.VITE_COGNITO_CLIENT_ID

const ApiUrls = {
  VITE_ATM_URL,
  VITE_ACCOUNTS_URL,
  VITE_TRANSFER_URL,
  VITE_LOAN_URL,
  VITE_COGNITO_USER_POOL_ID,
  VITE_COGNITO_CLIENT_ID
};

export default ApiUrls;
